language: cpp
sudo: false

os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt: &gcc5
     packages:
       - gcc-4.8
       - clang-3.7
       - libstdc++
     sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.7


install:
  - if [ ! "$(ls -A cmake-3.4.0-Linux-x86_64)" ]; then
      wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz
      && tar xf cmake-3.4.0-Linux-x86_64.tar.gz
      && rm cmake-3.4.0-Linux-x86_64.tar.gz;
    fi

before_script:
  - if [ "$CXX" == "clang++" ]; then
        export CXXCOMPILER="clang"
        && export CC="clang-3.7"
        && export CXX="clang++-3.7"
        && clang-3.7 --version
        && clang++-3.7 --version
        && find / | grep clang;
    fi
  - if [ "$CXX" == "g++" ]; then
        export CXXCOMPILER="gcc"
        && export CC="gcc-4.8"
        && export CXX="g++-4.8"
        && gcc-4.8 --version
        && find / | grep g++-4.8;
    fi
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - ../cmake-3.4.0-Linux-x86_64/bin/cmake ..

script:
  - make

cache:
  directories:
    - cmake-3.4.0-Linux-x86_64